### ISSUE TITLE
Do you mind me forking and reviving this project?

### ISSUE THREAD

**Issue by yodaluca23** [Theoteno/NitroLess#3]
Do you mind me forking and reviving this project? I'll give credit, and link to this original, I have already begun a little bit [here](https://github.com/yodaluca23/NitroLess), but wanted to ask before I start putting it out anywhere...

**Comment by theoteno** [comment]
Feel free to use the project in the spirit of open source, keeping the source available for everyone. I'd also pick a license which keeps all changes public, like GPL 3.0.
